### ISSUE TITLE
Support for Multi-git-repo setups

### ISSUE THREAD

**Issue by Hasibii** [SanderRonde/VSCode-Gerrit#23]
Hello!

Great work with this extension.

I'm currently working with a multi repo setup and get:
`Multi-git-repo setups are not supported`

Support for this setup would appreciated.

**Comment by SanderRonde** [comment]
Hmm I'm wondering how your multi-git-repo setup is organized. Is there a single repo that uses gerrit? Are there multiple? If it's just one (and this is a common pattern) I could consider just adding a `gitRootPath` setting and that would be all that's really needed.

**Comment by Hasibii** [comment]
```
Project_1 (repo)
-> lib1 (submodule)
Project_2 (repo)
->lib2 (submodule)
Project_3 (repo)
->lib1 (submodule)
->lib2 (submodule)
lib1 (repo)
lib2 (repo)
```

Everything is manged by a gerrit instance

**Comment by SanderRonde** [comment]
So if I understand correctly there's multiple gerrit projects (hosted on one instance) right? So multiple git roots that you all use?

**Comment by art-ignatev** [comment]
Hi!
I really enjoy using your extension.
Working with multi-repo setups is a must for me. 
Have you had a chance to work on that functionality?

**Comment by SanderRonde** [comment]
Hi, I'm still trying to work out what such a workflow looks like and what I need to do to support it (and whether that means it's worth it). What would you expect the extension to do?
- Have a setting called `currentGitRoot` that you can change with some `Gerrit: change current git root` command. All commands/actions are executed relative to `currentGitRoot`.
- Make it so that every command that is ambiguous in git root (for example the change selector in the bottom left) also asks for which git root it should be ran at the time of running it.

The first one sounds relatively easy while the second requires quite an overhaul (and is probably not worth it)

**Comment by art-ignatev** [comment]
Can't tell for everyone, but for me the first option is quite enough.

**Comment by SanderRonde** [comment]
There is now support for it in the latest release (`1.2.7`). It will first go over every repo to find out which ones are gerrit repos. If only one of them is a gerrit repo it will use that one. If there's more than one, you'll be prompted to pick one :)

**Comment by art-ignatev** [comment]
Thanks :)

**Comment by emirkmo** [comment]
Hi can you please document how to use the multirepo setup? Should I give the endpoint of the specific repo in multirepo or relative url from the endpoint?

**Comment by SanderRonde** [comment]
I think you won't have to give it anything, it'll just detect the .gitreview files in the repos and prompt you to pick a repo. Is that not working?
