### ISSUE TITLE
Got 401 with correct creds\url 

### ISSUE THREAD

**Issue by mikitakalinovsky** [SanderRonde/VSCode-Gerrit#24]
Hi! Im new in vscode, and previously worked with android studio. I tried to configure gerrit for my project, but unsuccessful, got Unauthorised.

There is my vscode config:

<img width="613" alt="Снимок экрана 2022-09-01 в 12 25 53" src="https://user-images.githubusercontent.com/71591796/187881974-e68118ff-0667-4e4a-86eb-0f3cbf90bfb4.png">

There is my android studio config with successful result:

<img width="613" alt="Снимок экрана 2022-09-01 в 12 30 56" src="https://user-images.githubusercontent.com/71591796/187881989-5b424fac-1ce0-4401-abfe-cdd5558149f8.png">

And there is vscode connection check result:

<img width="613" alt="Снимок экрана 2022-09-01 в 12 29 43" src="https://user-images.githubusercontent.com/71591796/187881986-df7435e2-5331-4f15-8857-14698ff54c20.png">

I found that plugin makes get request to http://gerritadress/a/config/server/version (found it in logs):

<img width="576" alt="Снимок экрана 2022-09-01 в 12 37 26" src="https://user-images.githubusercontent.com/71591796/187883213-427ec907-77a6-483d-a124-04b69462666d.png">

But i have no access to this endpoint with my account.. And i dont understand why plugin tries to reach this endpoint, because AS plugin requested only url from config.

Can you help me with this?

**Comment by SanderRonde** [comment]
I'm pretty sure you should always have access to `${yourGerritURL}/a/config/server/version` if you have configured your username and password correctly. As far as I know, any logged-in account has access to that endpoint. This is the reason why it's requested, to check whether you have API access at all, without potentially making a request to something that might be access-restricted.

Can you check whether you can access the URL in your browser? It should work since gerrit remembers your logged-in account. If not, can you check whether you can access `${yourGerritURL}/a/changes/` (remember the trailing /). You should definitely be able to make this request since that just shows you your changes.

**Comment by SanderRonde** [comment]
I'll close this issue since it seems to be stale

**Comment by ronnieandsandy** [comment]
I get the same message (401 unauthorized) as [mikitakalinovsky](https://github.com/mikitakalinovsky).
From a browser, ${yourGerritURL}/a/config/server/version downloads a version.json file, and ${yourGerritURL}/a/changes/ downloads a download.json file, which is a .json summary of my changes. We may have an additional layer of security that is needed for vscode v the browser

**Comment by SanderRonde** [comment]
Are you sure your username and password are correct? Can you maybe replicate the request in something like postman to isolate what is going wrong? Could indeed be that there's an additional layer of security but theoretically the `/a` endpoint uses the exact same logic as the HTTP API.

**Comment by ronnieandsandy** [comment]
I've tried to login about 50 times with the same creds I use to login using the browser, so I think I've gotten that right at least once. We have SSH keys setup for our server, and my experience with other IDEs and their plugins has been the SSH key password is required to complete the connection. I also tried this (vscode) plugin with a password-less ssh key setup, with the same negative result. I do understand this is a simple http get test, so I'm not sure why it would fail either. If time permits, I'll try to diagnose with postman, as you suggest, but I'll need to get postman installed by our IT team first. Lastly, our gerrit server is apparently 3.3.3, and I see this plugin supports gerrit 3.4 or later (https://github.com/SanderRonde/VSCode-Gerrit/issues/35)
![image](https://user-images.githubusercontent.com/10871002/228955954-38cbd8ac-665b-407d-a786-3c04c9fd12a9.png)

**Comment by SanderRonde** [comment]
Are you sure the password you use to log in to gerrit is also the password used for the HTTP credentials (so the one over at `/settings/#HTTPCredentials`)? It is indeed possible the use the SSH key too, but functionality of the SSH API is very limited compared to the HTTP API. Indeed the minimum version is 3.4, maybe 3.3.3 works too but I'm not too sure since I haven't tested it.
