### ISSUE TITLE
Getting RequestError: Socket is closed (503) for /changes and /version apis

### ISSUE THREAD

**Issue by saket-narlawar** [SanderRonde/VSCode-Gerrit#27]

**Comment by SanderRonde** [comment]
Hmm that's strange. Could be related to [this issue](https://github.com/sindresorhus/got/issues/1171) since that's the XHR library I'm using. Would you be willing to share with me the URL of your gerrit server so I can try replicating it? It could be an issue specific to this host or not. If you want to you can send it to me in a DM instead of over here (maybe Discord or Twitter).

**Comment by SanderRonde** [comment]
Closing this issue since it's become stale
