### ISSUE TITLE
Allow viewing and commenting on commit message

### ISSUE THREAD

**Issue by LiquidFire** [SanderRonde/VSCode-Gerrit#44]
Currently there seems to be no way to view or comment on the commit message of a review.

It would be great if this was possible, e.g. by exposing the pseudo-file `/COMMIT_MSG` as the Gerrit web UI does.

**Comment by LiquidFire** [comment]
The instance I use is running Gerrit 3.6.6 and does have a working `/COMMIT_MSG`, at least from the web UI. I haven't checked if anything is different via the API - are you saying for you it's broken through the API, or in general?

**Comment by SanderRonde** [comment]
For me it's broken in general (so the web UI too). But if it's supposed to work I'll add support for it in the extension. Will implement soon :)

**Comment by SanderRonde** [comment]
I've (sort of) implemented it. I can't fully test it because of the bug in my Gerrit version. Would you mind answering a few questions for me so I can verify if it works? The questions:
- Can you do the following for one of your patches with a commit message?
  - Go to the patch
  - Open devtools
  - Open some file (not the commit message)
  - Go to the network panel in your devtools. It'll list something like `https://{your_host}/changes/{project_name}~{change_number}/revisions/{revision_number}/{file_path}/diff?{some_query_params}`. What happens if you visit that URL in your browser? It should download a JSON file containing the diff.
  - What then happens if you visit that same URL but replace everything at the end (the `diff` and stuff after that) with `content`? It should open a TXT file containing a base64 encoded version of the file.
  - Now what happens if you replace the {file_path} with `COMMIT_MSG` here? (and maybe try `/COMMIT_MSG` too). In my case I get `ERR_INVALID_RESPONSE` but hopefully you don't.
- I've attached the new build of the extension. Can you try it out and see if you can see the new "commit message"  entry under changes in the list view? It'll hide it if the API fails so it's sort of expected behavior if it's not there. Good to know: the extension is attached as a zip file because github doesn't allow attaching `.vsix` files. Just rename it from `.zip` to `.vsix` and you can install it just fine :)

Thanks in advance!


[vscode--gerrit-1.2.12-test.zip](https://github.com/SanderRonde/VSCode-Gerrit/files/12507771/vscode--gerrit-1.2.12-test.zip)
