### ISSUE TITLE
Add support for cookie-based authentication

### ISSUE THREAD

**Issue by acarlson1029** [SanderRonde/VSCode-Gerrit#50]
Instead of sending the request with `username:password` I'd like to use a cookie for access.

The following works for me:

```
curl -H 'Cookie: <token>' -X GET "<host>/a/config/server/version"
```

Alternatively providing a cookie file:

```
curl -b <cookie_file> -X GET "<host>/a/config/server/version"
```

**Comment by SanderRonde** [comment]
Good idea, I've made a patch implementing this. Should be live soon :)

**Comment by acarlson1029** [comment]
@SanderRonde could the extension also support the `cookie_file` directly?

Currently it's hardcoding 'Cookie: GerritAccount=<token>', but this doesn't work on some OAuth setups that have a different cookie name.

**Comment by SanderRonde** [comment]
Could you use extraCookies for that? Perhaps even set up something that will rewrite your settings.json whenever the cookie file changes? Right now the extension does cache the cookie config until editor restart, so if your auth token changes multiple times a day that won't work very well. But I'm open to adding a bit of code that will invalidate the cookie config when the editor settings change.

I'm a bit wary to add cookie file parsing since I think it's probably not something a lot of people will use, and it could add some extra code around the cookie parser.
