### ISSUE TITLE
Repositories break with mandatory "a/" path for authenticated URLs

### ISSUE THREAD

**Issue by Mattadore** [SanderRonde/VSCode-Gerrit#59]

**Comment by SanderRonde** [comment]
Hey can you expand a bit on why this is needed? How does this break repositories and how is it that they don't need the `a/`? I thought it was mandatory for all authenticated API calls

**Comment by Mattadore** [comment]
I am not sure about the official gerrit specification, but I know for a fact it does not work without this change with Android gerrit repositories.

**Comment by SanderRonde** [comment]
Ah yeah you're right. I think they are indeed doing something strange (looks like a fork of gerrit). I do think that the AOSP is a big enough project that this is a valid thing to have as a setting. Two things still:
- Would you mind splitting up #61 into two PRs? Since they're mentioned in two different issues it's just a bit easier to separate the two code changes as well. (and that allows this one to be merged earlier than the other).
- Do you have any insight into whether this is a common pattern among other projects? What I'm afraid of is that some other project has decided to use `/b/` instead of `/a/` and this setting will have to change from "disable a/" to a "specify authenticated prefix" setting. I'm won't blame you if you don't know, I'd have no clue where to find this either but maybe you have encountered some.

If we can't really find any other variations (so no `/b/`-like) then I think the current approach is fine :)

**Comment by Mattadore** [comment]
- I can split the patches for sure, that's reasonable. I probably should have to begin with.
- I think changing from a boolean to an "authPath" or something, with default "a/" is super reasonable. It's about the same amount of work and much more flexible.
- 
- I'll update the PRs.

**Comment by SanderRonde** [comment]
Awesome, sounds good

**Comment by SanderRonde** [comment]
Both changes should be live in version `1.1.31` now
