### ISSUE TITLE
The 'Push for Review' button is not functioning

### ISSUE THREAD

**Issue by shaochencc** [SanderRonde/VSCode-Gerrit#63]
Why is there no response after clicking the 'Push for Review' button? I've already confirmed that I'm connected to the Gerrit server because I can see the previously merged commits in the repository.
![Snipaste_2024-04-18_12-26-23](https://github.com/SanderRonde/VSCode-Gerrit/assets/98878767/118a7a7a-6349-4e30-bdfe-45c4e84cb296)

**Comment by SanderRonde** [comment]
What clicking that command does is really just running `git review` in your terminal, in addition to a few other git-related things. It does not use the HTTP API since pushing changes through it is not possible. Does running `git review` normally work for you? I've published a new version of the extension (`1.1.30`) that should have improved logging and the UI around this feature. Can you check if those logs help you out in any way?

**Comment by shaochencc** [comment]
If I use the command line, I can submit code for review using git review. However, after clicking the button in this plugin, the code submission wasn't successful. I'll try out your latest version. Thank you!

**Comment by SanderRonde** [comment]
Is there no other visual feedback happening? No popup coming up in the notification center when you click the button? If so I'll make a debug build for you to figure out what's going wrong.

**Comment by shaochencc** [comment]
When I click the button, a notification pops up in the notification center saying 'Push for Review successful', but in reality, it hasn't been submitted

**Comment by SanderRonde** [comment]
Not sure what that could be... I've created a debug build for you that can help me answer some questions. Could you install it for me and show me the result of the logs? You can find the logs by, in VSCode, going to `Help` -> `Toggle developer tools` and then looking for any logs containing `[GERRIT]` (you can use the filter up above). I've attached the extension as a `.zip` file since github doesn't allow uploading of `.vsix` files. You'll have to rename it to `.vsix` again and then you can install it in your editor.

Thanks a lot!

[vscode--gerrit-1.2.32.zip](https://github.com/SanderRonde/VSCode-Gerrit/files/15098906/vscode--gerrit-1.2.32.zip)

**Comment by shaochencc** [comment]
![image](https://github.com/SanderRonde/VSCode-Gerrit/assets/98878767/4b3cb5cf-7333-4abc-bc77-14df166c102b)
According to your request, please help check if the log feedback indicates that the default branch is specified as 'master.' How can I choose the branch I want to submit?

**Comment by SanderRonde** [comment]
What do you normally use to push for review? The extension just runs `git-review` without any other arguments. You can test it out by doing that (running `git-review`) in a terminal and seeing what it says :)

**Comment by shaochencc** [comment]
Hello! Thanks to your guidance, I've realized that there's no 'master' branch in my repository, which is why my submissions weren't successful. I'll specify the branch for submission in the .gitreview file, as you suggested. Thank you very much for your help! This plugin is really amazing!

**Comment by SanderRonde** [comment]
Glad to hear you've found the issue, I'll close this issue then. Of course feel free to re-open if it still doesn't work.
