### ISSUE TITLE
Topic field automatically filled with change id

### ISSUE THREAD

**Issue by joguy56** [SanderRonde/VSCode-Gerrit#82]
Hello, 

I noticed that the review’s topic field  is currently filled with the change id. 

See:

![image](https://github.com/user-attachments/assets/6ecaf7d8-59a8-4e86-a642-5ed8fbfba9b4)

In the case of my team, the topic is really a specific keyword used for linking reviews that may be from different repos between themselves. So, in our usage, it is a single string that we may choose to fill or not.

Could it be possible to leave empty, or even let the user choose the topic name in the review panel for example ?

**Comment by SanderRonde** [comment]
How did you create this change? If just using the "push for review" button then it should only run `git review` in your terminal. Any topic-creation would then happen from there. Does this happen the moment you hit the "push for review" button in the review panel? If so that should indeed not be intentional

**Comment by SanderRonde** [comment]
In that case all the extension does is running `git-review` with no arguments in the terminal (in the background). Any topics etc that appear should appear as a result of what git-review is doing, which the extension has no further control over. Probably best to check out whether this also happens when just running `git-review` and debugging from there. I'm not entirely sure what setting to use in git-review to stop this, although the documentation does hint at `-T` "disabling auto-generated topic" so it might be that. If you can confirm that I could maybe add a setting for adding extra arguments to `git-review`, where you could use `-T`.

**Comment by joguy56** [comment]
Hi!

I tried to call gerrit-review by hand, and I confirm that using the -T flag avoids an automatic topic to be set.

It would be great to find a way to have the choice to include a topic or not.

**Comment by SanderRonde** [comment]
This is now possible in the latest version (`1.2.47`) which was just published using the `gerrit.pushForReviewArgs` configuration option. Just making that `['-T']` should fix your issue.
